networks:
  backend-network:
    driver: bridge
    
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  minio:
    image: bitnami/minio:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - backend-network
    volumes:
      - 'minio_data:/data'
    env_file:
      - .env

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - backend-network

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .env
    networks:
      - backend-network

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  minio_data:
    driver: local
