networks:
  localstack-net:
    name: localstack-net
    driver: bridge
  minio_network:
    name: minio_network
    driver: bridge

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: bitnami/minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minio_network
    volumes:
      - 'minio_data:/data'
    env_file:
      - docker.env

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass not_a_production_pass
    volumes:
      - redis:/data

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - docker.env

volumes:
  postgres:
    name: backend-db
  redis:
    driver: local
  minio_data:
    driver: local
